# Generated by Django 5.2.1 on 2025-06-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvenement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEvenement.chargedecommunication')),
            ],
            options={
                'verbose_name': 'Modèle de notification',
                'verbose_name_plural': 'Modèles de notification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataires', models.ManyToManyField(to='GestionEvenement.abonne')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEvenement.chargedecommunication')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
