# Generated by Django 5.2.3 on 2025-06-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvenement', '0003_evenement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='modere',
            field=models.BooleanField(default=False, help_text='Indique si le commentaire a été modéré'),
        ),
    ]
